name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}  # DataSource URL
      DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}  # DataSource password
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}  # JWT secret key
      JWT_VALIDITY: ${{ secrets.JWT_VALIDITY }}  # JWT validity

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'  # Updated to JDK 20
          distribution: 'adopt'

      - name: Configure Maven settings
        run: |
          echo "<settings><activeProfiles><activeProfile>github</activeProfile></activeProfiles><profiles><profile><id>github</id><properties><datasource.url>${DATASOURCE_URL}</datasource.url><datasource.password>${DATASOURCE_PASSWORD}</datasource.password><jwt.secret.key>${JWT_SECRET_KEY}</jwt.secret.key><jwt.validity>${JWT_VALIDITY}</jwt.validity></properties></profile></profiles></settings>" > ~/.m2/settings.xml

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Package application
        run: mvn package
